### ISSUE TITLE
No such file or directory ./prod.aci

### ISSUE THREAD

**Issue by Rob-pw** [odino/rkd#3]
https://github.com/odino/rkd/blob/d2c061c90418e5289f6647438e8116cf61d4da3c/cmd/build.go#L86

I believe this line is causing error:
```
rkd up
/root/.rkd/prod-bf3b63b754b857fb21ee5e6502e7a753.aci already built
Building /root/.rkd/dev-b61fc978a0187de3455b6667537a047c.aci
acbuild begin ./prod.aci
begin: no such file or directory: ./prod.aci
acbuild end
end: no build in progress in this working dir - try "acbuild begin"
panic: exit status 1 [recovered]
	panic: exit status 1

goroutine 1 [running]:
github.com/odino/rkd/utils.Execute(0xc42000ca00, 0x2, 0x2, 0x6616a0, 0xc42000e010, 0x6616e0, 0xc42000e018, 0x6616e0, 0xc42000e020)
	/home/odino/projects/go/src/github.com/odino/rkd/utils/utils.go:66 +0x159
github.com/odino/rkd/cmd.acbuild(0xc4200498c8, 0x1, 0x1)
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/build.go:35 +0x309
github.com/odino/rkd/cmd.buildAci.func2()
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/build.go:65 +0x77
panic(0x593d20, 0xc42000c9e0)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/odino/rkd/utils.Execute(0xc42001ab40, 0x3, 0x3, 0x6616a0, 0xc42000e010, 0x6616e0, 0xc42000e018, 0x6616e0, 0xc42000e020)
	/home/odino/projects/go/src/github.com/odino/rkd/utils/utils.go:66 +0x159
github.com/odino/rkd/cmd.acbuild(0xc420049c00, 0x2, 0x2)
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/build.go:35 +0x309
github.com/odino/rkd/cmd.buildAci(0x5a1fd0, 0x3)
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/build.go:86 +0x375
github.com/odino/rkd/cmd.glob..func1(0x678460, 0x695050, 0x0, 0x0)
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/build.go:23 +0x54
github.com/odino/rkd/cmd.glob..func2(0x678460, 0x695050, 0x0, 0x0)
	/home/odino/projects/go/src/github.com/odino/rkd/cmd/up.go:19 +0x57
github.com/spf13/cobra.(*Command).execute(0x678460, 0x695050, 0x0, 0x0, 0x678460, 0x695050)
	/home/odino/projects/go/src/github.com/spf13/cobra/command.go:660 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x678240, 0x5a1ff1, 0x3, 0x0)
	/home/odino/projects/go/src/github.com/spf13/cobra/command.go:735 +0x339
github.com/spf13/cobra.(*Command).Execute(0x678240, 0x0, 0x0)
	/home/odino/projects/go/src/github.com/spf13/cobra/command.go:694 +0x2b
main.main()
	/home/odino/projects/go/src/github.com/odino/rkd/main.go:12 +0x31
```

**Comment by Rob-pw** [comment]
Using: rkd-linux-386-0.1.0.gz, acbuild-v0.4.0.tar.gz, rkt_1.28.1-1_amd64.deb, go1.6.2 linux/amd64.

I have files such as: `/root/.rkd/prod-bf3b63b754b857fb21ee5e6502e7a753.aci` being made.
